menu:
  Home: /
  GitHub: https://github.com/getscissorhands/Scissorhands.NET

# duoshuo comment
duoshuo: false
duoshuo_name: 

# disqus comment
disqus: false
disqus_shortname: 

# google analytics
googleTrackId: 
